{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ required "A valid .Values.postgresql.auth.postgresPassword entry is required!" .Values.postgresql.auth.postgresPassword | quote }}
  password: {{ required "A valid .Values.postgresql.auth.password entry is required!" .Values.postgresql.auth.password | quote }}
{{- end }}
